Check that a pool have at least one worker,
pioardi/poolifier pull request #213
Opened 2021-02-21 11:22 UTC by jerome-benoit

Signed-off-by: Jérôme Benoit <jerome.benoit@sap.com>

## PR Checklist

- [ ] Please add a description of your changes.
- [ ] We need your changes to come with unit tests in order to keep this project in quality and easy to maintain.
- [ ] Please add a link to the open issue or task that this pull request will resolve.
- [ ] Add a note to the changelog to indicate the change.

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

If yes please indicate it and migration info into the CHANGELOG.md file.

---

2021-02-21 12:02 UTC, Shinigami92 commented
What's with **dynamic** pools where `numberOfWorkers === 0`?

2021-02-21 12:04 UTC, Shinigami92 commented
Please also add tests for at least following cases:
1. Verify the check itself
2. Verify that a dynamic pool can have min 0 workers
3. Verify that a fixed pool must have at least 1 worker

2021-02-21 12:07 UTC, jerome-benoit commented
> Please also add tests for at least following cases:
> 
> 1. Verify the check itself
> 2. Verify that a dynamic pool can have min 0 workers
> 3. Verify that a fixed pool must have at least 1 worker

We first need to merge the PR that implement strategies on worker choice and add `isDynamic()` method. Otherwise code will be duplicated.

2021-02-21 13:10 UTC, pioardi submitted a review, later dismissed

2021-02-21 13:14 UTC, Shinigami92 commented
@pioardi You don't need to approve draft PRs because your approval gets stale when new commits come into it

2021-02-21 19:02 UTC, jerome-benoit commented
I do not understand why sonarcloud coverage is failing, the branches added are checked in unit tests.

2021-02-21 19:27 UTC, Shinigami92 commented on src/pools/abstract-pool.ts
> +    if (numberOfWorkers === undefined) {
```suggestion
    if (numberOfWorkers == null) {
```

2021-02-21 19:27 UTC, Shinigami92 commented on src/pools/abstract-pool.ts
> +    } else if (!this.isDynamic() && numberOfWorkers <= 0) {
```suggestion
    } else if (!this.isDynamic() && numberOfWorkers === 0) {
```

or

```suggestion
    } else if (!this.isDynamic() && numberOfWorkers < 1) {
```

2021-02-21 19:29 UTC, Shinigami92 commented on tests/pools/abstract/abstract-pool.test.js
> +const { FixedClusterPool } = require('../../../lib/index')
I think you can merge this to `const { FixedClusterPool, FixedThreadPool } = require('../../../lib/index')`

2021-02-22 08:47 UTC, Shinigami92 commented
@jerome-benoit Did you know you can apply the suggested changes via the GitHub Web interface? On the files tab you can also apply the changes in batch at once.

---

Theoretically the code is okay
But we need to find out why the coverage dropped to 68.4%
This way it is not acceptable to merge currently :slightly_frowning_face:

2021-02-22 08:58 UTC, jerome-benoit commented
It's a bug on the static analyser.

2021-02-22 16:24 UTC, Shinigami92 requested changes

2021-02-22 16:24 UTC, Shinigami92 commented on tests/pools/abstract/abstract-pool.test.js
>        const pool = new StubPoolWithIsMainMethod(1, '').toThrowError()
This test doesn't look right to me :thinking:  
the `.toThrowError()` should be called on `expected` and not inside it

I could be wrong, but also I think just calling `.toThrowError()` with no `new Error(...)` argument always returns `true` :confused:  
This is really odd by mocha but I think it is this way :slightly_frowning_face:

2021-02-22 16:24 UTC, Shinigami92 commented on tests/pools/abstract/abstract-pool.test.js
> +      ).toThrowError(
And this may be the error here :warning: 
It should be called on expected and not inside it! The tests are running without doing anything!

2021-02-22 17:10 UTC, Shinigami92 commented
@jerome-benoit You need to add a new test-case for `"Cannot instantiate a pool without specifying the number of workers"`

2021-02-22 17:11 UTC, Shinigami92 commented on tests/pools/abstract/abstract-pool.test.js
> -          'Cannot instantiate a pool without specifying the number of workers'
The old test-case for this did never run and it was not correct

2021-02-22 17:21 UTC, Shinigami92 commented
Now that we already check src directly instead of lib, should we write our tests also in typescript? That way the bug would be seen much better and earlier because the function toThrowError() does not exist on the pool but the return of expect

2021-02-22 17:41 UTC, Shinigami92 commented
Ah so it was a copy paste error beforehand I think

2021-02-22 17:41 UTC, Shinigami92 commented
`100.0% Coverage` great job to us :tada:

2021-02-22 17:43 UTC, pioardi commented
It looks great, I will need more time to review that better.
Feel free to go ahead if both of you are confident :)

2021-02-22 17:43 UTC, Shinigami92 approved these changes

2021-02-22 17:44 UTC, Shinigami92 commented
> It looks great, I will need more time to review that better.
> Feel free to go ahead if both of you are confident :)

We are not in a haste, so if you want a second approval on your side, we should do that

2021-02-22 17:53 UTC, jerome-benoit commented
> It looks great, I will need more time to review that better.
> Feel free to go ahead if both of you are confident :)

It's just sanity checks for pool creation parameters. 

I think the next step can be to provide default values if they are not provided: 
+ fixed: numberOfThreads = number of CPUs the OS see
+ dynamic: min = 0 and max = number of CPUs the OS see

through a kind of configurations mask object for pool parameters.

2021-02-22 17:53 UTC, Shinigami92 approved these changes

2021-02-22 17:57 UTC, Shinigami92 commented
> I think the next step can be to provide default values if they are not provided:
> 
> * fixed: numberOfThreads = number of CPUs the OS see
> * dynamic: min = 0 and max = number of CPUs the OS see
> 
> through a kind of configurations mask object for pool parameters.

I'm not sure if this would be good :thinking:  
A ThreadPool could run more threads that CPUs in OS
and maybe a ClusterPool should not use the whole system by default
If users want to do this, they should just pass the values and read them out on their own
We could provide examples for that and document it, but default values could not be so good

2021-02-22 18:01 UTC, pioardi approved these changes
It is a great job, thank you guys for that

2021-02-22 18:02 UTC, pioardi commented
> > It looks great, I will need more time to review that better.
> > Feel free to go ahead if both of you are confident :)
> 
> It's just sanity checks for pool creation parameters.
> 
> I think the next step can be to provide default values if they are not provided:
> 
> * fixed: numberOfThreads = number of CPUs the OS see
> * dynamic: min = 0 and max = number of CPUs the OS see
> 
> through a kind of configurations mask object for pool parameters.

We can think about that later on yes :)

2021-02-22 18:02 UTC, merged